"""make job and plan/user timestamps timezone-aware

Revision ID: 34aed8f22dbb
Revises: 84e179c9bb52
Create Date: 2026-09-17 16:29:56.114976

Fixes a real production-fragility risk found while hardening
cleanup_expired_results.py: created_at/updated_at were plain `timestamp
without time zone` columns. The application always writes them via
datetime.now(timezone.utc) (see models.py's _utcnow()), but a
`timestamp without time zone` column has no timezone metadata at all --
psycopg2 converts an aware Python datetime to the *database session's*
configured timezone (this project's local dev Postgres: Asia/Calcutta)
before storing it as a naive wall-clock value. Every write and every
comparison (this cleanup script, QuotaService.get_status's day/month
cutoffs) happened to stay internally consistent only because every
connection uses the same server-configured session timezone -- a real
but *latent* landmine: a different session timezone (a differently
configured Postgres server, a connection with an overridden `TimeZone`
setting) would silently shift every comparison by that offset.

DATA SAFETY: switching to `timestamptz` (Postgres's actual UTC-normalized,
unambiguous instant type) via a plain `ALTER COLUMN ... TYPE timestamptz`
with NO explicit USING clause is safe *specifically* because every
existing row was written under this same stable session timezone
setting -- Postgres's own default behavior for this exact ALTER is to
reinterpret the existing naive values using the current session
timezone, which is exactly the same interpretation that was implicitly
used when they were originally written. Verified directly (not assumed)
before writing this migration: inserted a known UTC instant into a
`timestamp without time zone` column, ran this exact ALTER with no
USING clause, and confirmed the recovered timestamptz value matched the
original UTC instant exactly (including microseconds), in both the
upgrade and downgrade directions, round-tripped twice. Do NOT add an
explicit `postgresql_using=...` clause here -- for this dataset, doing
so would risk *double*-shifting values that are already correctly
interpreted by Postgres's default behavior.

This migration does not change any Python-level behavior: _utcnow()
already returned an aware UTC datetime; only the column's own semantics
change, from "trust the session timezone to interpret this" to
"already an unambiguous instant."
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34aed8f22dbb'
down_revision: Union[str, Sequence[str], None] = '84e179c9bb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('plans', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('plans', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('jobs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('jobs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
