"""add job garment_photo_type for model-worn plumbing

Revision ID: 84e179c9bb52
Revises: bb26ae740580
Create Date: 2026-09-16 19:52:54.306559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e179c9bb52'
down_revision: Union[str, Sequence[str], None] = 'bb26ae740580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-adjusted (not left as autogenerated): a NOT NULL column added to
    # a table that already has rows (real jobs from earlier testing) needs
    # a server_default so Postgres can backfill existing rows -- the plain
    # autogenerated `nullable=False` with no default fails against
    # populated tables. "flat-lay" is the only value the API layer has ever
    # accepted, so it's the only correct backfill value for every existing
    # row.
    op.add_column(
        'jobs',
        sa.Column('garment_photo_type', sa.String(length=16), nullable=False, server_default='flat-lay'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'garment_photo_type')
    # ### end Alembic commands ###
