"""add plans table and job client_ip for usage quotas

Revision ID: bb26ae740580
Revises: 6221ad01543a
Create Date: 2026-09-15 15:15:58.361140

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb26ae740580'
down_revision: Union[str, Sequence[str], None] = '6221ad01543a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


plans_table = sa.table(
    "plans",
    sa.column("name", sa.String),
    sa.column("max_generations_per_day", sa.Integer),
    sa.column("max_generations_per_month", sa.Integer),
    sa.column("max_num_timesteps", sa.Integer),
    sa.column("created_at", sa.DateTime),
    sa.column("updated_at", sa.DateTime),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('max_generations_per_day', sa.Integer(), nullable=True),
    sa.Column('max_generations_per_month', sa.Integer(), nullable=True),
    sa.Column('max_num_timesteps', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_plans'))
    )
    # ### end Alembic commands ###

    # Hand-added (not autogenerated): seed the two plans with the brief's own
    # example numbers (section 23) as starting defaults — an operator can
    # change these with an UPDATE statement, no code change or deploy
    # required. Must happen before the FK below: existing 'free' users
    # (there are some, from earlier milestones' testing) need a matching row
    # to reference, or Postgres rejects the constraint.
    now = datetime.now(timezone.utc)
    op.bulk_insert(
        plans_table,
        [
            {
                "name": "free",
                "max_generations_per_day": 5,
                "max_generations_per_month": None,
                "max_num_timesteps": 30,
                "created_at": now,
                "updated_at": now,
            },
            {
                "name": "premium",
                "max_generations_per_day": None,
                "max_generations_per_month": 100,
                "max_num_timesteps": 50,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('client_ip', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_jobs_client_ip'), 'jobs', ['client_ip'], unique=False)
    op.create_foreign_key(op.f('fk_users_plan_plans'), 'users', 'plans', ['plan'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_plan_plans'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_client_ip'), table_name='jobs')
    op.drop_column('jobs', 'client_ip')
    op.drop_table('plans')
    # ### end Alembic commands ###
