"""add password reset tokens table

Revision ID: d2aad5003996
Revises: 97144edca52b
Create Date: 2026-09-17 20:20:57.031623

Adds secure password reset (forgot-password / reset-password). A new table,
not columns on `users`, because a user can have at most one *outstanding*
token by design (see services/password_reset_service.py's issue_reset_token,
which deletes any earlier unused one before creating a new one) but the
history of past, now-consumed tokens is still a genuinely separate resource
from the account itself, with its own lifecycle (expires_at/used_at) and
its own cleanup sweep (cleanup_expired_password_reset_tokens) — cramming
that onto `users` the way idempotency's three columns fit onto an existing
`jobs` row (97144edca52b) would just be a worse fit here, not a simpler one.

Only a SHA-256 hash of the token is stored (token_hash), never the raw
value that goes out in the email — same hash-not-raw-value principle as
jobs.idempotency_fingerprint. `used_at` (rather than a separate boolean or
deleting the row on use) is what lets reset_password's single UPDATE ...
WHERE used_at IS NULL AND expires_at > now() both claim and permanently
invalidate a token atomically, relying on Postgres's own row-level locking
for race-safety under concurrent requests, the same style of database-level
guarantee as `ix_jobs_idempotency_active`'s partial unique index — just an
UPDATE...WHERE claim instead of a unique-index conflict, since "at most one
claimant wins" here doesn't need a uniqueness constraint at all, just a
WHERE clause that stops matching once claimed.

`ondelete='CASCADE'` on user_id, consistent with `jobs.user_id`: deleting an
account leaves no orphaned reset tokens behind.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2aad5003996'
down_revision: Union[str, Sequence[str], None] = '97144edca52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
