"""add admin audit log table

Revision ID: e1f5538acd61
Revises: e94aa22bee59
Create Date: 2026-09-18 16:49:27.344873

Admin/Operations follow-up: a persistent, append-only record of
security-sensitive admin actions (account disable/enable, an
admin-promotion bootstrap, a plan-limit edit) -- see
app/db/models.py's AdminAuditLog docstring for the full field-by-field
reasoning and app/services/admin_service.py's record_audit_log() for the
only application-code writer (backend/scripts/promote_admin.py is the
other, for the one action with no HTTP-authenticated admin session to
attribute it to).

`admin_user_id` is a nullable FK with ON DELETE SET NULL, not CASCADE --
deleting the acting admin's account must not delete the historical record
of what they did. `details` is `JSONB` with a `'{}'::jsonb` server
default (needed the same way every other nullable=False add against a
possibly non-empty table does, even though this is a brand-new table with
no existing rows to backfill) -- reviewed at every call site to hold only
safe, non-secret context, never a password/JWT/reset-token/other
credential. Two indexes: `created_at` for the log's natural
newest-first listing order, `admin_user_id` for "what did this admin do."
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1f5538acd61'
down_revision: Union[str, Sequence[str], None] = 'e94aa22bee59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name=op.f('fk_admin_audit_log_admin_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit_log'))
    )
    op.create_index(op.f('ix_admin_audit_log_admin_user_id'), 'admin_audit_log', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_created_at'), 'admin_audit_log', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_audit_log_created_at'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_admin_user_id'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
